[phases.setup]
nixPkgs = ["openjdk", "tomcat", "wget", "curl", "gnutar"]

[phases.build]
cmds = [
  "wget https://downloads.apache.org/tomcat/tomcat-10/v10.1.39/bin/apache-tomcat-10.1.39.tar.gz",
  "tar -xvzf apache-tomcat-10.1.39.tar.gz",
  "mv apache-tomcat-10.1.39 tomcat"
]

[start]
cmd = "tomcat/bin/catalina.sh run"
